<?php

namespace Wink\Tests\Unit;

use PHPUnit\Framework\TestCase;
use Wink\Images\HouseGrade;

class HouseGradeTest extends TestCase
{
    private const CONFIG = [
        'target_luma' => 132,
        'clamp' => [0.75, 1.35],
        'saturation' => 0.82,
        'navy' => [14, 34, 52],
        'navy_strength' => 0.07,
        'contrast' => 1.06,
    ];

    public function test_it_matches_the_pillow_reference_pixel_for_pixel()
    {
        // Generated by tests/fixtures/generate_reference.py from grade.py.
        $cases = json_decode(file_get_contents(__DIR__.'/../fixtures/house-grade-pillow.json'), true);

        foreach ($cases as $index => $case) {
            $this->assertSame($case['expected'], (new HouseGrade(self::CONFIG))->apply($case['input']), "Case {$index}");
        }
    }

    public function test_luma_uses_pillows_fixed_point_weights()
    {
        $this->assertSame(0, HouseGrade::luma(0, 0, 0));
        $this->assertSame(255, HouseGrade::luma(255, 255, 255));
        $this->assertSame(76, HouseGrade::luma(255, 0, 0));
        $this->assertSame(150, HouseGrade::luma(0, 255, 0));
    }

    public function test_blend_truncates_and_clips_like_pillow()
    {
        $this->assertSame(127, HouseGrade::blend(0, 255, 0.5));
        $this->assertSame(255, HouseGrade::blend(0, 250, 1.35));
        $this->assertSame(0, HouseGrade::blend(200, 5, 1.06));
    }

    public function test_exposure_is_skipped_for_a_black_image()
    {
        $black = array_fill(0, 30, 0);

        $this->assertSame($black, (new HouseGrade(self::CONFIG))->exposure($black));
    }
}
